### ISSUE TITLE
error writing to influxdb

### ISSUE THREAD

**Issue by billimek** [trojanc/node-influx-uptimerobot#3]
Thank you so much for creating this.  It's awesome to annotate graphs with this data.

It seems to find the data and send it, but the container also throws a bunch of errors such as:

```
Error: {"error":"partial write: field type conflict: input field \"reason\" on measurement \"logs\" is type float, already exists as type string dropped=1"}

    at /usr/src/node-influx-uptimerobot/node_modules/influx/index.js:130:23
    at InfluxRequest._parseCallback (/usr/src/node-influx-uptimerobot/node_modules/influx/lib/InfluxRequest.js:122:10)
    at Request._callback (/usr/src/node-influx-uptimerobot/node_modules/influx/lib/InfluxRequest.js:111:10)
    at Request.self.callback (/usr/src/node-influx-uptimerobot/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/src/node-influx-uptimerobot/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/src/node-influx-uptimerobot/node_modules/request/request.js:1079:12)
Error: {"error":"partial write: field type conflict: input field \"reason\" on measurement \"logs\" is type string, already exists as type float dropped=4"}

    at /usr/src/node-influx-uptimerobot/node_modules/influx/index.js:130:23
    at InfluxRequest._parseCallback (/usr/src/node-influx-uptimerobot/node_modules/influx/lib/InfluxRequest.js:122:10)
    at Request._callback (/usr/src/node-influx-uptimerobot/node_modules/influx/lib/InfluxRequest.js:111:10)
    at Request.self.callback (/usr/src/node-influx-uptimerobot/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/src/node-influx-uptimerobot/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/src/node-influx-uptimerobot/node_modules/request/request.js:1079:12)
```

... etc

Are you familiar with this?

**Comment by trojanc** [comment]
I see now that this can happen.
Uptimerobot's poorly documented API sometimes sends a string, or a number for the `monitors[].logs[].reason.code` field. 
It looks like the values I get - atleast from my account -  is all numeric, or numeric text...But because these fields aren't even in the API document, I don't know what the values can be...
I'll force them to string which I guess is more save.

Here is a snippet of my response I get from uptimerobot API (truncated tree...)
```json
                {
                    "type": 2,
                    "datetime": 1524093122,
                    "duration": 1530786,
                    "reason": {
                        "code": "200",
                        "detail": "OK"
                    }
                },
                {
                    "type": 1,
                    "datetime": 1524093075,
                    "duration": 47,
                    "reason": {
                        "code": "333333",
                        "detail": "Connection Timeout"
                    }
                },
                {
                    "type": 2,
                    "datetime": 1522073197,
                    "duration": 2019878,
                    "reason": {
                        "code": 2,
                        "detail": "Connection Timeout"
                    }
                }
```
Here you can see the response had the following values for the reason code
- "200"
- "333333"
- 2

So I guess my question now is...is this field really useful?!
I you are able to find any docs on this fields please let me know. Or if there is other info you'd like this to log as well.
